baseURl = "https://bertelsen.ca/"
languageCode = "en-us"
title = "@beb"
theme = "hugo-tania"

[menu]
  [[menu.header]]
    name = "Notes"
    url = "/articles/"
  [[menu.header]]
    name = "About"
    url = "/about/"

[params]
  [params.socialOptions]
    stack-overflow = "https://stackoverflow.com/users/170352/brandon-bertelsen"
    github = "https://github.com/1beb"
    linkedin = "https://linkedin.com/in/bbertelsen"
    twitter = "https://twitter.com/1beb"
    email = "brandon@bertelsen.ca"


[markup]
[markup.highlight]
  noClasses = false
  lineNos = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
